### ISSUE TITLE
Loading into saves with multiclass will cause the character level increase to the sum of all multiclass, not before using multiclass

### ISSUE THREAD

**Issue by Naruto1135** [cabarius/ToyBox#100]
As title suggests.

**Comment by quasihtonder** [comment]
Same

**Comment by LadyAlekto** [comment]
Also on area change and when story based level up happens

**Comment by DreamTourist** [comment]
Bug is kind of FIXED in v1-2-10.
The fix also provides a way to avoid the Subclass reversion bug in Character Creation.

**Comment by LadyAlekto** [comment]
Works at least for the MC but not companions

Tried to set up wendy and aru with hunter subclasses set to gestalt, only my main correctly gets the missing levels and on level up effects

(tested on new game, giving seelah cavalier ontop, and a old save where i was multiclassed)

**Comment by cabarius** [comment]
I fixed the level calculation by add in the check boxes in  Party Editor > Char > Classes.   I plan to make level up on gestalt flag classes automatically and so forth.

I need to investigate why gestalt is not working on companions.

**Comment by LadyAlekto** [comment]
Had some time for further testing, it seems to apply (somewhat randomly) when they get a new level and you do quicksave/quickload with it enabled (so id look for the check somewhere where it loads the applied character levels)

But they still dont level up the chosen second classes, and im still not over the fact that wendy is a fighter and neither hunter nor rogue
